name: 🚀 Run

on:
  workflow_dispatch:

jobs:
  run:
    name: 🚀 Run
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🚀 Run
        shell: bash
        run: |
          python3 test.py
<<<<<<< HEAD

      
=======
          
>>>>>>> 2aa82d6562b1338997a4d4ec61b17b5bf119db70
